name: CI-CD

on:
  push: 
    branches: ['main']

jobs: 
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev libsdl2-ttf-dev
      - name: build cxt
        run: |
          make cxt
        env:
          CC: clang

